version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "5099:2181"
  kafka1:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 194.61.2.84
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "main_topic:1:3, dead_letter:1:3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    build: .
    ports:
      - "9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 194.61.2.84
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "main_topic:1:3, dead_letter:1:3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    build: .
    ports:
      - "9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: 194.61.2.84
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "main_topic:1:3, dead_letter:1:3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock